export const GET_USERS = 'GET_USERS';
export const USERS_FETCHED = 'USERS_FETCHED';
export const FETCH_USERS_FAILED = 'FETCH_USERS_FAILED';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const CLEAR_CURRENT_USER = 'CLEAR_CURRENT_USER';
export const DELETE_USER = 'DELETE_USER';
export const REMOVE_FROM_DELETED = 'REMOVE_FROM_DELETED';
export const REMOVE_TOAST = 'REMOVE_TOAST';
